global using Carter;
global using Mapster;
global using MediatR;
global using FluentValidation;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.IdentityModel.Tokens;
global using depensio.Application.UserCases.Auth.DTOs;
global using BuildingBlocks.Responses;
global using depensio.Application.DTOs;
